### PR TITLE
fix: patch light mode no longer supported issue

### LINKED ISSUE #128: Fix light mode no longer supported issue
### Reproduction steps

Change system mode to light, but the background is no longer in light mode. 

### Expected Results

Both dark mode and light mode works. 

### Actual Results

Only dark mode works now. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TenzDelek**
fixes #128 

## What was the issue?
the issue was mainly in the mapPage.css
where the contributor uses 
```js
body {
  background-color: #121212;
  color: #ffffff;
}
```
which made the overall page color static and overlaps the theme.

## solution
we uses the theme to dynamically change the color base on it. 

## Screenshot
Screenshot 2025-03-01 at 3 59 08 PM
Screenshot 2025-03-01 at 3 59 14 PM
Screenshot 2025-03-01 at 3 59 26 PM

## Result
now the repo support both dark and light theme

### CODE REVIEW

**Comment by TenzDelek** [comment]
@krisstern  this pr will solve the issue happening . let me know if changes are needed. if all looks good , after this merge i will make changes in the #121

File: src/pages/map.jsx [hunk 1]
```diff
@@ -127,9 +127,9 @@ const MapPage = () => {
       <Seo title={title} pathname="/" />
       <div className="container">
         <div className="row text-center">
-          <div className="col">
-            <h1>Jenkins Is The Way</h1>
-            <h2>Latest Jenkins User Stories</h2>
+          <div className="col ">
```
Comment (krisstern) [inline src/pages/map.jsx:130]:
```suggestion
          <div className="col">
```

**Review by krisstern — CHANGES_REQUESTED** [review]

**Comment by krisstern** [comment]
Thanks @TenzDelek! On the surface this looks like what we wanted. Let me review it over the weekend more carefully.

**Comment by TenzDelek** [comment]
> Thanks @TenzDelek! On the surface this looks like what we wanted. Let me review it over the weekend more carefully. 

Sure 🙏

File: src/pages/map.jsx (hunk 1 above)
Comment (TenzDelek) [reply src/pages/map.jsx]: changes reflected

**Review by krisstern — APPROVED** [review]
Thanks for the PR @TenzDelek!
